sudo: required

language: rust
rust:
    - nightly
cache:
    - cargo: true

branches:
    only:
        - master

install:
    - sudo apt-get install -y "linux-headers-$(uname -r)"
    - type -p cargo-install-update || cargo install --force cargo-update
    - |
      if type -p cargo-xbuild; then
          cargo install-update -i cargo-xbuild
      else
          cargo install --force cargo-xbuild
      fi
    - rustup component add rust-src

script:
    - ./tests/run_tests.sh

after_failure:
    - dmesg

notifications:
    email: false
