sudo: required

language: rust
rust:
    - nightly
cache: cargo

matrix:
    include:
        - env: MODULE_DIR=hello-world MODULE=helloworld
        - env: MODULE_DIR=static-filesystem MODULE=staticfilesystem

install:
    - cargo install cargo-xbuild
    - rustup component add rust-src

script:
    - cd $MODULE_DIR
    - RUST_TARGET_PATH="$(pwd)/.." cargo xbuild --target x86_64-linux-kernel-module
    - make
    - sudo insmod "${MODULE}.ko"
    - sudo rmmod "$MODULE"
