matrix:
    include:
        - dist: xenial

language: rust
rust:
    - nightly-2019-09-11
cache:
    - cargo: true

branches:
    only:
        - master

install:
    - sudo apt-get install -y "linux-headers-$(uname -r)" realpath
    - rustup component add rust-src rustfmt clippy

script:
    - ./tests/run_tests.py
    - |
      for p in . hello-world tests/*; do
        if [ -d "$p" ]; then
          (cd "$p" && cargo fmt --all -- --check) || exit 1
        fi
      done
    - env CARGO_TARGET_DIR=tests/target cargo clippy-preview -Z unstable-options -Z build-std=core,alloc --target=x86_64-linux-kernel -- -D warnings

after_failure:
    - dmesg

notifications:
    email: false
